### ISSUE TITLE
Homegenie service stops responding

### ISSUE THREAD

**Issue by ngineerken** [genielabs/HomeGenie#361] opened 2019-02-01 05:03 UTC
### Expected behavior
HomeGenie just runs

### Actual behavior
HomeGenie runs about 3 days before becoming unresponsive

### Steps to reproduce the problem starting from a fresh install

  1. Start the Pi
  2. Services are running
  3. After 3 days HG has stopped responding

### Specifications

  - Version: 1.2-stable.35
  - Operating System: Rasbian Stretch with all the latest updates & kernel too
  - .Net/Mono runtime version:
  - Hardware configuration: Raspberry Pi 3 W PiDrive using Zwave+ protocal

#### Additional configuration notes
the Pi is also running as a weather station using weewx, this is why i use a PiDrive as i was burning through SD Cards

**Comment by ngineerken** [comment] 2019-02-02 02:10
I'm at Version: 1.2-stable.35
Setting a reboot cron job is not the answer to an issue that has arisen , it's only a band-aid to the bug.

**Comment by tuicemen** [comment] 2019-02-02 04:34
@ngineerken your original post stated you were at Version: 1.1-stable.527 and my work around was what I did for that version. I've not had that issue since moving to genes newer versions and moving to a newer Mono version. It's only a bug if others are seeing it, Gene put out version 1.2-stable 36 today so you might try that if you've not already.

**Comment by tuicemen** [comment] 2019-02-02 05:50
@mralapete, Band aid fixes (work arounds) are of value if they get ones system working until a permanent fix is found.
@ngineerken  besides the log file what does a "sudo systemctl status homegenie.service" report when this happens?

**Comment by tuicemen** [comment] 2019-02-02 14:04
@mralapete  no I'm not missing the point. Originally @ngineerken posted they were running 1.1-stable.527 maybe that was a typo which they edited to fix after my first response. 


Since Gene never posted what was fixed or added in v36 how can you be sure updating will not fix the issue. @ngineerken never posted HG was crashing just that the service was not responding. A log file may or may not reveal the issue as may a status request to the service.

**Comment by ngineerken** [comment] 2019-02-02 16:04
I had logging on, now disabled. I also update to v36 and now lets see how things go.

Thanks for all the help

**Comment by tuicemen** [comment] 2019-02-02 16:49
Did the logging show anything (errors)?

**Comment by mralapete** [comment] 2019-02-02 16:50
@tuicemen at the risk of repeating myself the logs will be helpful to determine what exactly is going on here. Unresponsive would indicate a crashed program. If you feel you can troubleshoot a system without them, particularly a server I will take my had off to you. Personally I prefer the log route rather than the crystal ball 

I imagine Gene and others would agree with this conclusion too and remember upgrading may only be hiding a bigger issue if it's not investigated properly. The fact that others have not reported an issue similar to @ngineerken leads me to think his issue is particular to his system only. Guesswork will not solve that problem.

I

**Comment by tuicemen** [comment] 2019-02-02 17:07
I'm not sure why you seem to always think I don't recommend logging! There is no use trying to debug a old version which I assumed @ngineerken was running from his original Post.
 I use to hate users posting bug reports for old versions of my software.
 Especially when I knew the issue wasn't present in the new version. That being said you'll notice I asked if  @ngineerken log showed anything!

**Comment by ngineerken** [comment] 2019-02-06 03:48
Well turning logging off did not help.

pi@raspberrypi:~ $ sudo systemctl status homegenie.service
● homegenie.service - LSB: Run HomeGenie
   Loaded: loaded (/etc/init.d/homegenie; generated; vendor preset: enabled)
   Active: **active (exited)** since Sat 2019-02-02 12:21:02 CST; 3 days ago
     Docs: man:systemd-sysv-generator(8)
  Process: 5624 ExecStop=/etc/init.d/homegenie stop (code=exited, status=0/SUCCE
  Process: 6079 ExecStart=/etc/init.d/homegenie start (code=exited, status=0/SUC
   CGroup: /system.slice/homegenie.service

**Comment by mralapete** [comment] 2019-02-06 10:55
Could you type mono —version at the terminal and paste the results here.

Have you sudo apt update and sudo apt upgrade recently. It may be worth doing to get the lastest version of your OS

Could you run HG in debug as follows

cd /usr/local/bin/homegenie
sudo mono HomeGenie.exe

and paste the results.

**Comment by tuicemen** [comment] 2019-02-06 13:30
> Does anyone need / want ogging?

Logging is helpful in situations like this it can point to the root cause of the issue. If you know what to look for.  This is why @mralapete & I asked what the logging showed and why @mralapete is asking you to run in debug mode and post the log.

Logging doesn't need to be running 24/7 unless your having problems. If the log file in HG shows nothing then a Debug logging using the command @mralapete posted usually will help.

**Comment by ngineerken** [comment] 2019-02-07 02:17
> On Feb 6, 2019, at 4:55 AM, mralapete <notifications@github.com> wrote:
> 
> Could you type mono —version at the terminal and paste the results here.
> 
> 
pi@raspberrypi:~ $ mono --version
Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       normal
	Notifications: epoll
	Architecture:  armel,vfp+hard
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen


> Have you sudo apt update and sudo apt upgrade recently. It may be worth doing to get the lastest version of your OS
> 
> I run this 2 to 3 times per week:
pi@raspberrypi:~ $ sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade
> Could you run HG in debug as follows
> 
> cd /usr/local/bin/homegenie
> sudo mono HomeGenie.exe
> 
> and paste the results.
> 
> 
pi@raspberrypi:/usr/local/bin/homegenie $ sudo mono HomeGenie.exe
﻿rmmod: ERROR: Module lirc_atiusb is not currently loaded
rmmod: ERROR: Module ati_remote is not currently loaded
rmmod: ERROR: Module rc_ati_x10 is builtin.

**Comment by tuicemen** [comment] 2019-02-07 17:35
@ngineerken  do you have HG password protected? You really should get more info then that.

**Comment by mralapete** [comment] 2019-02-07 17:39
Those errors relate to the blacklisting of drivers which were conflicting with the X10 CM19 driver. Not sure those rmmod commands are required anymore.

I'm assuming you had logging enabled and examined the output in /usr/local/bin/homegenie/log/

To examine the last part of the log file before it hung just use the tail -n 20 homegenie.log and paste the results. This might catch the offending process which is causing system hang.

I assume you're running the WeeWX on the same Pi. Is it still running after HG has hung. Is it feeding from your own weather station or from the likes WU. I imagine it's quite resource hungry as its constantly logging.

I noticed you're using a PiDrive too. It might be worth swapping back to an SD card temporarily and run your setup to see if it still crashes.

Would you consider off loading WeeWX to a separate Pi and passing whatever you need from it to the Pi running HG.

**Comment by ngineerken** [comment] 2019-02-09 15:48
> On Feb 6, 2019, at 4:55 AM, mralapete <notifications@github.com> wrote:
> 
> Could you type mono —version at the terminal and paste the results here.
> 
> Have you sudo apt update and sudo apt upgrade recently. It may be worth doing to get the lastest version of your OS
> 
> Could you run HG in debug as follows
> 
> cd /usr/local/bin/homegenie
> sudo mono HomeGenie.exe
> 
> and paste the results.
> 
> 
pi@raspberrypi:~ $ cd /usr/local/bin/homegenie/log/
pi@raspberrypi:/usr/local/bin/homegenie/log $ tail -n 20 homegenie.log
2019-02-02 09:58:16.8539 Error HomeAutomation.HomeGenie.Automation	93	Method 'string.Split' not found.	Exception.StackTrace	  at HomeGenie.Automation.ProgramManager.RoutePropertyChangedEvent (System.Object eventData) [0x000c3] in <d65005afed7646669abaa4da7905999c>:0 
 Trace Complete
2019-02-02 09:58:16.7478 Trace [[[ EN2019-02-02 09:58:17.3491 Trace WaitAck
2019-02-02 09:58:17.3491 Trace Sending Message (Node=12, CallbackId=9E, Function=SendData, CommandClass=Version)
2019-02-02 09:58:17.3499 Debug 01-09-00-13-0C-02-86-11-05-9E-E7
2019-02-02 09:58:17.3514 Debug 06
2019-02-02 09:58:17.4517 Debug 01-04-01-13-01-E8
2019-02-02 09:58:17.4522 Debug ZWaveMessage (RawData=01-04-01-13-01-E8)
2019-02-02 09:58:17.4522 Debug ZWaveMessageessage (RawData=01-04-01-13-01-E8)
Updated (NodeId=12, Parameter=ManufacturerSpecific, Value=ZWaveLib.CommandClasses.ManufacturerSpecificInfo)
19-02-02 09:58:15.5448 Trace SendDa2019-02-02 09:58:16.8507 Info HomeAutomation.ZWave	12	ZWave Node	ZWaveNode.ManufacturerSpecific	0060:000C:0001
2019-02-02 09:58:16.8539 Error HomeAutomation.HomeGenie.Automation	93	Method 'string.Split' not found.	Exception.StackTrace	  at HomeGenie.Automation.ProgramManager.RoutePropertyChangedEvent (System.Object eventData) [0x000c3] in <d65005afed7646669abaa4da7905999c>:0 
 Trace Complete
2019-02-02 09:58:16.7478 Trace [[[ EN2019-02-02 09:58:17.3491 Trace WaitAck
2019-02-02 09:58:17.3491 Trace Sending Message (Node=12, CallbackId=9E, Function=SendData, CommandClass=Version)
2019-02-02 09:58:17.3499 Debug 01-09-00-13-0C-02-86-11-05-9E-E7
2019-02-02 09:58:17.3514 Debug 06
2019-02-02 09:58:17.4517 Debug 01-04-01-13-01-E8
2019-02-02 09:58:17.4522 Debug ZWaveMessage (RawData=01-04-01-13-01-E8)
2019-02-02 09:58:17.4522 Debug ZWaveMessagepi@raspberrypi:/usr/local/bin/homegenie/log $

**Comment by ngineerken** [comment] 2019-02-09 15:54
> On Feb 7, 2019, at 11:39 AM, mralapete <notifications@github.com> wrote:
> 
> Those errors relate to the blacklisting of drivers which were conflicting with the X10 CM19 driver. Not sure those rmmod commands are required anymore.
> 
> I'm assuming you had logging enabled and examined the output in /usr/local/bin/homegenie/log/
> 
> To examine the last part of the log file before it hung just use the tail -n 20 homegenie.log and paste the results. This might catch the offending process which is causing system hang.
> 
> I assume you're running the WeeWX on the same Pi. Is it still running after HG has hung. Is it feeding from your own weather station or from the likes WU. I imagine it's quite resource hungry as its constantly logging.
> 
> I noticed you're using a PiDrive too. It might be worth swapping back to an SD card temporarily and run your setup to see if it still crashes.
> 
> Would you consider off loading WeeWX to a separate Pi and passing whatever you need from it to the Pi running HG.
> 
> 
If I have to split the weather station & Home Genie I might consider another Home Automation. But the ones that I have experience in the past were clunky as compared to HG.

**Comment by genemars** [comment] 2019-02-09 16:11
@ngineerken from your logs it seems you're running an old versiono of mono ad I see "Method 'string.Split' not found".
Mono 4.6.2 is recommended.

**Comment by genemars** [comment] 2019-02-09 16:13
@genemars ... ok just noticed from your previous message that you're already running mono 4.6.2. So this error is very odd.

**Comment by genemars** [comment] 2019-02-09 16:15
@ngineerken did you try also latest HomeGenie release?

**Comment by ngineerken** [comment] 2019-02-09 16:26
> On Feb 9, 2019, at 10:15 AM, Generoso Martello <notifications@github.com> wrote:
> 
> @ngineerken <https://github.com/ngineerken> did you try also latest HomeGenie release?
> 
> 
I have HomeGenie Version v1.2-stable.37 installed

**Comment by tuicemen** [comment] 2019-03-14 18:24
@ngineerken are you still experiencing this?

**Comment by ngineerken** [comment] 2019-03-15 00:23
Yes it is till happening and even more frequent like ever 2 days now and it is with HG 1.2.stable 39

**Comment by tuicemen** [comment] 2019-03-15 00:42
Does  weewx also stop?
Have you tried running just HG or  weewx on the pi  and the other on another machine (pi)?

**Comment by ngineerken** [comment] 2019-03-15 00:54
Weewx does not stop. I have not had a chance to try another pi at this time.  I may try it this weekend, just running from an SD card.

**Comment by genemars** [comment] 2019-03-17 13:53
Hi @ngineerken can you try disabling the "Devices & Things" -> "UPnP Emulation" program?

**Comment by ngineerken** [comment] 2019-03-18 02:21
Started the SD card on a new Raspberry pi 3B+ 
now i have the Beta offering multiple installs
https://github.com/genielabs/HomeGenie/issues/373

**Comment by tuicemen** [comment] 2019-03-26 19:00
@ngineerken did disabling the "UPnP emulation" program fix your HG hang ups?

**Comment by ngineerken** [comment] 2019-03-27 02:20
I have HomeGenie Version v1.3-beta.2 running on a new SD card on a Pi3b+, and is running fine so far.

**Comment by tuicemen** [comment] 2019-03-27 10:45
Gene did state a bug in the UPnP program was causing HG to hang in another thread. 
I had to disable that as well but for a different reason. I think it was so the echo bridge would work so that maybe why I didn't get the issue you had. Nice to see it has been working for you with out hanging so far.

**Comment by noliono** [comment] 2019-04-20 21:46
> I have HomeGenie Version v1.3-beta.2 running on a new SD card on a Pi3b+, and is running fine so far.
> Yes I have UPnP disabled too.

So issue can be clode no? @ngineerken 
Resolve by deactivating emulation upnp..

**Comment by genemars** [comment] 2019-04-22 07:50
I think this can be closed now.

**Closed by genemars** 2019-04-22 07:50 UTC
