### ISSUE TITLE
Widgets show temperature in Farenheit when they should be in Centegrate

### ISSUE THREAD

**Issue by RichCattell** [genielabs/HomeGenie#76] opened 2014-12-22 13:51 UTC
This appears to be an intermittant bug, and im not sure when or what causes it to happen, but...
all of my widgets that show temperature, i.e. thermostats and my 3-in1 motion sensors all now show their temperature in Farenheit whereas they used to show in Centigrade. However the values shown in the group list still show in Centigrade.

**Comment by genielabs** [comment] 2015-02-05 13:48
This should be solved by now. I'm closing it, just reopen if the issue is still there.

**Comment by RichCattell** [comment] 2015-02-05 17:21
Im still getting this issue in r474, so it looks as though his hasn't been fixed yet.

**Comment by genielabs** [comment] 2015-08-13 22:52
duplicate #196

**Closed by genielabs** 2015-08-13 22:52 UTC
Labels: duplicate
