### ISSUE TITLE
Beta 60 Shutter widget

### ISSUE THREAD

**Issue by dakriege** [genielabs/HomeGenie#471] opened 2023-10-09 10:55 UTC
**Version**
1.60 Beta

Updated Shutter widget is working. Open / Close and Partial  using the slider. 

![image](https://github.com/genielabs/HomeGenie/assets/25644492/0c5e4542-f62a-4c85-adb4-9444343c38ec)

**Comment by dakriege** [comment] 2023-10-09 11:07
I forgot to mention that the Service never restarted after doing the 1.60 Beta update. I restarted the Service and the Update completed. 

An issue that I found with the Shutter wizard is that if I open it with Chrome on my Laptop it displays a different looking Shutter widget.

![image](https://github.com/genielabs/HomeGenie/assets/25644492/5793dc3b-6923-42a3-8df3-92fb3c6c27e3)

I've tried clearing the cache and doing a hard reload. 

If I open the 'Developer' mode on Chrome it doesn't report any errors. 

If I open HomeGenie with Microsoft Edge it works fine. 

![image](https://github.com/genielabs/HomeGenie/assets/25644492/6412ced2-5855-4316-964b-d04344994207)

**Comment by genemars** [comment] 2023-10-09 13:28
Did you also try **clearing site data**?

![Schermata del 2023-10-09 15-19-36](https://github.com/genielabs/HomeGenie/assets/6654265/95b4ac11-b3d0-4aeb-9fba-d54ddd6dc507)

Once this happened to me as well, but then I was not able to reproduce the issue again.

**Comment by dakriege** [comment] 2023-10-09 15:44
Cleared site data. That fixed it.

**Comment by dakriege** [comment] 2023-10-10 10:44
One thing I noticed on the ZWave widgets is that they don't seem to update in the background or do a refresh when you open the Dashboard.  When you open the ZWave Dashboard the Widgets are shown in their last state. Using the new Shutter widget the Dashboard shows that one of the Shades is closed but it's actually open. It shows the last state as Closed a day ago.
I have the ZWave Query Level program enabled and running.  Since you can use the remote control that came with the Shades the state may be open / closed or partially closed so the Dashboard will need to refresh when it's opened.

**Comment by genemars** [comment] 2023-10-10 17:15
I would suggest to deactivate the query level program and instead configure your Z-Wave devices to auto-report level changes to association group 1 (that is the z-wave controller). The parameter number to enable level report should be in the device manual.
For example [this door sensor](https://manual.zwave.eu/backend/make.php?lang=en&sku=DEVE9355&cert=ZC10-14090007&type=mini) uses parameter **10** to enable/disable automatic report of open/close status. 
Anyway, I think the real problem here is that the dashboard "snapshot" stored client-side is taking precedence over the actual devices status loaded from server (kind of desync).
You can verify this by opening directly in the browser the API URL that returns the devices status, you'll see that devices properties are the correct one with actual data updated real-time.

`http://ip_address:port/api/HomeAutomation.HomeGenie/Config/Modules.List`

I thought that was already fixed, but I must have missed something :)
Tomorrow I'll look into this and fix it.

**Comment by dakriege** [comment] 2023-10-11 10:59
I did the Modules list as your recommended. 
The status level for the Shutter widget that is Open but shows Closed is 0.  

![image](https://github.com/genielabs/HomeGenie/assets/25644492/ecca886b-6e1d-47c1-bfb1-ac620450cba2)

I am unable to open the HomeGenie home page. 

That has happened several times and requires a re-start on the service. 

My home page URL is http://192.168.10.15:5006/ which I assumed defaults to index.html

http://192.168.10.15:5006/app/index.html is displayed in the URL parameter 

Sometimes the Browser displays

http://192.168.10.15:5006/app/home/Z-Wave

The HomeGenie - YoT page just spins forever and never opens.

**Comment by genemars** [comment] 2023-10-11 11:38
That gives me more clues. So the device seems not sending any basic report.
You can try the API manually:
`http://server_address/api/HomeAutomation.ZWave/4/Basic.Get`
And see what the response value is.
So having the manual of this device could help a lot to find out how to configure automatic report. Searching internet for this device manufacturer specific gives me no results. Not even a brand name.
About the homepage not opening and loading spinner never disappearing, the only reason I can think of is that still AVG blocks the service for some reason.
It would be helpful if you enable logging and then run HomeGenie in a terminal window instead of a background service, Just to find out if any error pops-up.

**Comment by dakriege** [comment] 2023-10-11 14:16
If I use the API and do the Basic.Get I get the current status and it updates the Widgets. 

 

I ordered a spare motor so I can do some testing without effecting the Blinds. 

 

I will see if there is a sticker with manufacturer info. 

 

Dave

**Comment by genemars** [comment] 2023-10-11 16:39
@dakriege 
I probably found the documentation of a similar device to yours:
https://www.opensmarthouse.org/zwavedatabase/1567
It seems that the parameters are not documented.
So the only thing you can do right now is adding the controller (node 1) to the association group 1 and then enable the `Z-Wave Level Polling` program as you did before since in this case is the only viable solution to synchronize the motor status with the UI.
Let me know if it works.

**Comment by genemars** [comment] 2023-10-20 10:31
I think this issue is now fixed by [v1.4.0-beta.61](https://github.com/genielabs/HomeGenie/tree/v1.4.0-beta.61)

**Closed** 2023-12-30 17:03 UTC
Labels: bug
